### ISSUE TITLE
Missing main.yml error !

### ISSUE THREAD

**Issue by dilipsharma2005** [jtyr/ansible-vmware_vm_provisioning#1]
Hi
I am getting below error. Please help
root@aci-ucs-jumpdesk:/home/cloudadmin# ansible-galaxy install jtyr.ansible_vmware_vm_provisioning
- downloading role 'ansible_vmware_vm_provisioning', owned by jtyr

downloading role from https://github.com/jtyr/ansible-vmware_vm_provisioning/archive/v1.0.0.tar.gz
 [WARNING]: - jtyr.ansible_vmware_vm_provisioning was NOT installed successfully: this role does not appear to have a meta/main.yml file.

**Comment by sernafa** [comment]
Hi,
I get same error:

$ ansible-galaxy install  jtyr.ansible_vmware_vm_provisioning                                                                                                                                                                                   
- downloading role 'ansible_vmware_vm_provisioning', owned by jtyr                                                                                                                                                                                                             
- downloading role from https://github.com/jtyr/ansible-vmware_vm_provisioning/archive/v1.0.0.tar.gz                                                                                                                                                                           
 [WARNING]: - jtyr.ansible_vmware_vm_provisioning was NOT installed successfully: this role does not appear to have a meta/main.yml file.

**Comment by jtyr** [comment]
Thanks for reporting this. I thought that was already fixed but I was wrong. Here is a PR which fixes it in Ansible:
https://github.com/ansible/ansible/pull/46505

**Comment by jtyr** [comment]
This issue will be fixed with the next Ansible release.
